name: plapt
channels:
  - conda-forge
  - pytorch
  - huggingface
  - defaults
dependencies:
  - python=3.11
  - pip
  - pytorch>=1.13.1
  - transformers
  - pandas
  - scipy
  - numpy>=1.17
  - biopython
  - rdkit>=2023.9.4
  - scikit-learn
  - requests
  - tqdm
  - pillow
  - pip:
    - onnxruntime
    - diskcache
    - datasets
    - evaluate
    - huggingface-hub
    - accelerate 
